Repository Souf-Project/Souf-BE, pull requests merged in 2025-06, with the labels that each got.

#66 [Fix] 공고문 crud 기능 수정
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/RecruitPopularityResDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/RecruitReqDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/RecruitResDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/RecruitSimpleResDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/entity/Recruit.java
  src/main/java/com/souf/soufwebsite/domain/recruit/entity/RegionType.java
  src/main/java/com/souf/soufwebsite/domain/recruit/entity/WorkType.java
  src/main/java/com/souf/soufwebsite/domain/recruit/repository/RecruitCustomRepositoryImpl.java
Labels: fix

#75 [Fix] 회원가입 로직 수정
  src/main/java/com/souf/soufwebsite/domain/member/controller/auth/AuthApiSpecification.java
  src/main/java/com/souf/soufwebsite/domain/member/controller/auth/AuthController.java
  src/main/java/com/souf/soufwebsite/domain/member/dto/ReqDto/SignupReqDto.java
  src/main/java/com/souf/soufwebsite/domain/member/exception/ErrorType.java
  src/main/java/com/souf/soufwebsite/domain/member/exception/NotVerifiedEmailException.java
  src/main/java/com/souf/soufwebsite/domain/member/service/MemberService.java
  src/main/java/com/souf/soufwebsite/domain/member/service/MemberServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/member/service/VerificationPurpose.java
Labels: fix

#85 [Fix] 지연 로딩 오류 수정
  src/main/java/com/souf/soufwebsite/domain/feed/dto/FeedDetailResDto.java
  src/main/java/com/souf/soufwebsite/domain/member/entity/Member.java
  src/main/java/com/souf/soufwebsite/domain/member/entity/MemberCategoryMapping.java
  src/main/java/com/souf/soufwebsite/domain/member/service/MemberServiceImpl.java
Labels: fix, refactor

#88 [Feat] 기존 회원의 권한 전환
  src/main/java/com/souf/soufwebsite/domain/member/controller/MemberApiSpecification.java
  src/main/java/com/souf/soufwebsite/domain/member/controller/MemberController.java
  src/main/java/com/souf/soufwebsite/domain/member/controller/auth/AuthApiSpecification.java
  src/main/java/com/souf/soufwebsite/domain/member/controller/auth/AuthController.java
  src/main/java/com/souf/soufwebsite/domain/member/dto/ReqDto/SendEmailReqDto.java
  src/main/java/com/souf/soufwebsite/domain/member/dto/ReqDto/SendModifyEmailReqDto.java
  src/main/java/com/souf/soufwebsite/domain/member/dto/ReqDto/VerifyEmailReqDto.java
  src/main/java/com/souf/soufwebsite/domain/member/exception/ErrorType.java
  src/main/java/com/souf/soufwebsite/domain/member/exception/NotValidEmailException.java
  src/main/java/com/souf/soufwebsite/domain/member/service/MemberService.java
  src/main/java/com/souf/soufwebsite/domain/member/service/MemberServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/member/service/VerificationPurpose.java
Labels: fix, refactor

#91 [Feat] 즐겨찾기 기능 구현
  src/main/java/com/souf/soufwebsite/domain/application/service/ApplicationServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/feed/dto/FeedReqDto.java
  src/main/java/com/souf/soufwebsite/domain/feed/service/FeedServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/file/service/FileService.java
  src/main/java/com/souf/soufwebsite/domain/member/controller/FavoriteController.java
  src/main/java/com/souf/soufwebsite/domain/member/controller/FavoriteMemberSuccessResponse.java
  src/main/java/com/souf/soufwebsite/domain/member/dto/ReqDto/FavoriteMemberReqDto.java
  src/main/java/com/souf/soufwebsite/domain/member/dto/ResDto/MemberResDto.java
  src/main/java/com/souf/soufwebsite/domain/member/entity/FavoriteMember.java
  src/main/java/com/souf/soufwebsite/domain/member/exception/ErrorType.java
  src/main/java/com/souf/soufwebsite/domain/member/exception/NotFoundFavoriteException.java
  src/main/java/com/souf/soufwebsite/domain/member/repository/FavoriteMemberRepository.java
  src/main/java/com/souf/soufwebsite/domain/member/repository/MemberCategoryMappingRepository.java
  src/main/java/com/souf/soufwebsite/domain/member/repository/MemberCustomRepository.java
  src/main/java/com/souf/soufwebsite/domain/member/repository/MemberCustomRepositoryImpl.java
  src/main/java/com/souf/soufwebsite/domain/member/repository/MemberRepository.java
  src/main/java/com/souf/soufwebsite/domain/member/service/FavoriteService.java
  src/main/java/com/souf/soufwebsite/domain/member/service/FavoriteServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/member/service/MemberCategoryServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/member/service/MemberServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/RecruitReqDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/RecruitResDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/RecruitSimpleResDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/repository/RecruitCustomRepositoryImpl.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitServiceImpl.java
  src/main/java/com/souf/soufwebsite/global/config/SecurityConfig.java
  src/main/java/com/souf/soufwebsite/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/souf/soufwebsite/global/security/UserDetailsServiceImpl.java
  src/test/java/com/souf/soufwebsite/domain/member/service/MemberCategoryServiceTest.java
Labels: fix, refactor

#95 [Fix] 채팅 보안 설정
  docker-compose.yml
  src/main/resources/application.yml
Labels: fix

#97 [Feat] 채팅 기능 반환값 구체화
  src/main/java/com/souf/soufwebsite/domain/chat/controller/ChatController.java
  src/main/java/com/souf/soufwebsite/domain/chat/controller/ChatRoomController.java
  src/main/java/com/souf/soufwebsite/domain/chat/dto/ChatMessageResDto.java
  src/main/java/com/souf/soufwebsite/domain/feed/dto/FeedDetailResDto.java
  src/main/java/com/souf/soufwebsite/domain/feed/service/FeedServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/member/controller/MemberController.java
  src/main/java/com/souf/soufwebsite/domain/member/dto/ResDto/MemberResDto.java
  src/main/java/com/souf/soufwebsite/domain/member/repository/MemberCustomRepositoryImpl.java
  src/main/java/com/souf/soufwebsite/domain/member/service/FavoriteServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/member/service/MemberService.java
  src/main/java/com/souf/soufwebsite/domain/member/service/MemberServiceImpl.java
Labels: feat
