Repository Souf-Project/Souf-BE, pull requests merged in 2025-07, with the labels that each got.

#101 [Feat] 동영상 업로드 로직 추가
  build.gradle
  src/main/java/com/souf/soufwebsite/domain/feed/dto/FeedResDto.java
  src/main/java/com/souf/soufwebsite/domain/feed/service/FeedServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/file/controller/FileApiSpecification.java
  src/main/java/com/souf/soufwebsite/domain/file/controller/FileController.java
  src/main/java/com/souf/soufwebsite/domain/file/controller/FileUploadSuccessMessage.java
  src/main/java/com/souf/soufwebsite/domain/file/dto/S3UploadPartsDetailDto.java
  src/main/java/com/souf/soufwebsite/domain/file/dto/S3VideoUploadSignedUrlReqDto.java
  src/main/java/com/souf/soufwebsite/domain/file/dto/VideoResDto.java
  src/main/java/com/souf/soufwebsite/domain/file/dto/VideoUploadCompletedDto.java
  src/main/java/com/souf/soufwebsite/domain/file/entity/MediaType.java
  src/main/java/com/souf/soufwebsite/domain/file/service/FileService.java
  src/main/java/com/souf/soufwebsite/domain/file/service/S3UploaderService.java
  src/main/java/com/souf/soufwebsite/global/config/S3Config.java
Labels: feat, refactor

#115 [Feat] 공고문 마감 기능 구현
  .github/workflows/CI-CD.yml
  .github/workflows/test-CI-CD.yml
  docker-compose.yml
  src/main/java/com/souf/soufwebsite/domain/member/dto/ReqDto/MemberIdReqDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/controller/RecruitApiSpecification.java
  src/main/java/com/souf/soufwebsite/domain/recruit/controller/RecruitController.java
  src/main/java/com/souf/soufwebsite/domain/recruit/entity/Recruit.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitService.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitServiceImpl.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: feat, refactor

#117 [Fix] 채팅별 아이디 반환
  .github/workflows/test-CI-CD.yml
  src/main/java/com/souf/soufwebsite/domain/chat/controller/ChatController.java
  src/main/java/com/souf/soufwebsite/domain/chat/controller/ChatFileApiSpecification.java
  src/main/java/com/souf/soufwebsite/domain/chat/controller/ChatRoomController.java
  src/main/java/com/souf/soufwebsite/domain/chat/dto/ChatMessageResDto.java
  src/main/java/com/souf/soufwebsite/domain/chat/service/ChatMessageService.java
Labels: fix

#124 [Fix] 인기 피드 및 공고문 조회 수정
  src/main/java/com/souf/soufwebsite/domain/feed/dto/FeedSimpleResDto.java
  src/main/java/com/souf/soufwebsite/domain/file/service/S3UploaderService.java
  src/main/java/com/souf/soufwebsite/domain/recruit/repository/RecruitCustomRepositoryImpl.java
  src/main/java/com/souf/soufwebsite/domain/recruit/repository/RecruitRepository.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitServiceImpl.java
Labels: fix

#139 Main 브랜치에 병함
  build.gradle
  src/main/java/com/souf/soufwebsite/domain/application/service/ApplicationServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/feed/service/FeedServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/member/controller/MemberApiSpecification.java
  src/main/java/com/souf/soufwebsite/domain/member/controller/MemberController.java
  src/main/java/com/souf/soufwebsite/domain/member/controller/auth/AuthApiSpecification.java
  src/main/java/com/souf/soufwebsite/domain/member/controller/auth/AuthController.java
  src/main/java/com/souf/soufwebsite/domain/member/service/MemberService.java
  src/main/java/com/souf/soufwebsite/domain/member/service/MemberServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/opensearch/EntityType.java
  src/main/java/com/souf/soufwebsite/domain/opensearch/OperationType.java
  src/main/java/com/souf/soufwebsite/domain/opensearch/controller/IndexAdminController.java
  src/main/java/com/souf/soufwebsite/domain/opensearch/controller/SearchController.java
  src/main/java/com/souf/soufwebsite/domain/opensearch/doc/FeedDoc.java
  src/main/java/com/souf/soufwebsite/domain/opensearch/doc/MemberDoc.java
  src/main/java/com/souf/soufwebsite/domain/opensearch/doc/RecruitDoc.java
  src/main/java/com/souf/soufwebsite/domain/opensearch/dto/SearchResDto.java
  src/main/java/com/souf/soufwebsite/domain/opensearch/event/IndexEvent.java
  src/main/java/com/souf/soufwebsite/domain/opensearch/event/IndexEventPublisherHelper.java
  src/main/java/com/souf/soufwebsite/domain/opensearch/listener/IndexListener.java
  src/main/java/com/souf/soufwebsite/domain/opensearch/service/IndexingService.java
  src/main/java/com/souf/soufwebsite/domain/opensearch/service/InitialIndexingService.java
  src/main/java/com/souf/soufwebsite/domain/opensearch/service/SearchService.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitServiceImpl.java
  src/main/java/com/souf/soufwebsite/global/common/mail/SesMailService.java
  src/main/java/com/souf/soufwebsite/global/config/AWSConfig.java
  src/main/java/com/souf/soufwebsite/global/config/OpenSearchConfig.java
  src/main/java/com/souf/soufwebsite/global/config/OpenSearchInitializer.java
  src/main/java/com/souf/soufwebsite/global/config/SecurityConfig.java
  src/main/java/com/souf/soufwebsite/global/util/SesTemplateUtil.java
  src/main/resources/application.yml
Labels: Upload Main branch

#144 Feat: slack 연동하기
  build.gradle
  src/main/java/com/souf/soufwebsite/domain/feed/controller/FeedController.java
  src/main/java/com/souf/soufwebsite/domain/file/entity/MediaType.java
  src/main/java/com/souf/soufwebsite/domain/member/service/MemberServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/recruit/controller/RecruitController.java
  src/main/java/com/souf/soufwebsite/global/redis/service/DistributedLockService.java
  src/main/java/com/souf/soufwebsite/global/slack/SlackConstant.java
  src/main/java/com/souf/soufwebsite/global/slack/service/SlackService.java
  src/main/resources/application-prod.yml
Labels: feat, refactor

#147 Fix: 동영상 파일 contenttype 수정
  src/main/java/com/souf/soufwebsite/domain/feed/controller/FeedController.java
  src/main/java/com/souf/soufwebsite/domain/feed/service/FeedServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/file/service/S3UploaderService.java
  src/main/java/com/souf/soufwebsite/domain/member/service/MemberServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/recruit/controller/RecruitController.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitServiceImpl.java
Labels: fix, refactor

#151 Fix: 동영상 썸네일 저장하기
  build.gradle
  src/main/java/com/souf/soufwebsite/domain/chat/controller/ChatFileController.java
  src/main/java/com/souf/soufwebsite/domain/feed/dto/FeedResDto.java
  src/main/java/com/souf/soufwebsite/domain/feed/service/FeedServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/file/dto/MediaResDto.java
  src/main/java/com/souf/soufwebsite/domain/file/dto/video/VideoDto.java
  src/main/java/com/souf/soufwebsite/domain/file/dto/video/VideoUploadCompletedDto.java
  src/main/java/com/souf/soufwebsite/domain/file/entity/Media.java
  src/main/java/com/souf/soufwebsite/domain/file/repository/MediaRepository.java
  src/main/java/com/souf/soufwebsite/domain/file/service/FileService.java
  src/main/java/com/souf/soufwebsite/domain/file/service/S3UploaderService.java
  src/main/java/com/souf/soufwebsite/global/common/mail/SesMailService.java
  src/main/java/com/souf/soufwebsite/global/config/AWSConfig.java
  src/main/java/com/souf/soufwebsite/global/config/RedisConfig.java
  src/main/java/com/souf/soufwebsite/global/ecs/ECSService.java
  src/main/java/com/souf/soufwebsite/global/sqs/ThumbnailEventListener.java
  src/main/resources/application.yml
Labels: feat, refactor

#155 Fix: 동영상 썸네일 조회 범위 수정
  src/main/java/com/souf/soufwebsite/domain/feed/service/FeedConverter.java
  src/main/java/com/souf/soufwebsite/domain/file/dto/MediaResDto.java
  src/main/java/com/souf/soufwebsite/domain/file/service/S3UploaderService.java
Labels: feat
