Repository Souf-Project/Souf-BE, pull requests merged in 2025-09, with the labels that each got.

#202 [FIX] 카카오 소셜로그인 오류
  src/main/java/com/souf/soufwebsite/domain/socialAccount/dto/SocialLoginResDto.java
  src/main/java/com/souf/soufwebsite/domain/socialAccount/service/SocialAccountService.java
Labels: refactor

#210 Fix: 인기 피드 response 값 수정
  src/main/java/com/souf/soufwebsite/domain/feed/dto/FeedSimpleResDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/controller/RecruitController.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/RecruitPopularityResDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/repository/RecruitRepository.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitScheduledService.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitServiceImpl.java
Labels: fix

#217 [FEAT] 테스트 커버리지 도입
  src/main/java/com/souf/soufwebsite/domain/application/exception/ErrorType.java
  src/main/java/com/souf/soufwebsite/domain/chat/controller/ChatRoomController.java
  src/main/java/com/souf/soufwebsite/domain/chat/entity/ChatRoom.java
  src/main/java/com/souf/soufwebsite/domain/chat/exception/ErrorType.java
  src/main/java/com/souf/soufwebsite/domain/chat/exception/NotChatMyselfException.java
  src/main/java/com/souf/soufwebsite/domain/chat/exception/NotChatRoomParticipantException.java
  src/main/java/com/souf/soufwebsite/domain/chat/exception/NotFoundChatRoomException.java
  src/main/java/com/souf/soufwebsite/domain/chat/exception/NotFoundParticipantException.java
  src/main/java/com/souf/soufwebsite/domain/chat/service/ChatRoomService.java
  src/main/java/com/souf/soufwebsite/domain/city/exception/ErrorType.java
  src/main/java/com/souf/soufwebsite/domain/city/exception/NotFoundCityDetailException.java
  src/main/java/com/souf/soufwebsite/domain/city/exception/NotFoundCityException.java
  src/main/java/com/souf/soufwebsite/domain/city/exception/RequiredCityDetailException.java
  src/main/java/com/souf/soufwebsite/domain/comment/exception/ErrorType.java
  src/main/java/com/souf/soufwebsite/domain/feed/exception/ErrorType.java
  src/main/java/com/souf/soufwebsite/domain/recruit/exception/ErrorType.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/report/exception/ErrorType.java
  src/main/java/com/souf/soufwebsite/domain/socialAccount/exception/ErrorType.java
  src/main/java/com/souf/soufwebsite/domain/socialAccount/exception/NotValidProviderException.java
  src/main/java/com/souf/soufwebsite/domain/socialAccount/exception/NotValidTokenException.java
  src/main/java/com/souf/soufwebsite/domain/socialAccount/service/SocialAccountService.java
Labels: fix, feat

#218 Fix/#216/인기 게시글 조회 기능 수정
  src/main/java/com/souf/soufwebsite/domain/feed/controller/FeedApiSpecification.java
  src/main/java/com/souf/soufwebsite/domain/feed/controller/FeedController.java
  src/main/java/com/souf/soufwebsite/domain/feed/entity/Feed.java
  src/main/java/com/souf/soufwebsite/domain/feed/repository/FeedRepository.java
  src/main/java/com/souf/soufwebsite/domain/feed/service/FeedScheduledService.java
  src/main/java/com/souf/soufwebsite/domain/feed/service/FeedService.java
  src/main/java/com/souf/soufwebsite/domain/feed/service/FeedServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/recruit/controller/RecruitApiSpecification.java
  src/main/java/com/souf/soufwebsite/domain/recruit/controller/RecruitController.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/req/RecruitReqDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/res/RecruitPopularityResDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/res/RecruitResDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/res/RecruitSimpleResDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/entity/Recruit.java
  src/main/java/com/souf/soufwebsite/domain/recruit/repository/RecruitCustomRepositoryImpl.java
  src/main/java/com/souf/soufwebsite/domain/recruit/repository/RecruitRepository.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitScheduledService.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitService.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitServiceImpl.java
  src/main/java/com/souf/soufwebsite/global/config/RedisConfig.java
  src/main/java/com/souf/soufwebsite/global/redis/service/DistributedLockService.java
  src/main/java/com/souf/soufwebsite/global/redis/util/CacheWarmUpRunner.java
  src/main/java/com/souf/soufwebsite/global/redis/util/RedisUtil.java
Labels: fix, refactor

#222 Hot fix: 공고문피드 생성 로직 오류 핫픽스
  src/main/java/com/souf/soufwebsite/domain/feed/dto/FeedReqDto.java
  src/main/java/com/souf/soufwebsite/domain/feed/dto/FeedUpdateReqDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/SortOption.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/req/MyRecruitReqDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/req/RecruitReqDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/req/RecruitSearchReqDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/entity/Recruit.java
Labels: fix

#229 Main에 merge
  src/main/java/com/souf/soufwebsite/domain/feed/controller/FeedApiSpecification.java
  src/main/java/com/souf/soufwebsite/domain/feed/controller/FeedController.java
  src/main/java/com/souf/soufwebsite/domain/feed/dto/FeedReqDto.java
  src/main/java/com/souf/soufwebsite/domain/feed/dto/FeedUpdateReqDto.java
  src/main/java/com/souf/soufwebsite/domain/feed/service/FeedService.java
  src/main/java/com/souf/soufwebsite/domain/feed/service/FeedServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/recruit/controller/RecruitApiSpecification.java
  src/main/java/com/souf/soufwebsite/domain/recruit/controller/RecruitController.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/req/RecruitReqDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/req/RecruitSearchReqDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/entity/Recruit.java
  src/main/java/com/souf/soufwebsite/domain/recruit/repository/RecruitCustomRepository.java
  src/main/java/com/souf/soufwebsite/domain/recruit/repository/RecruitCustomRepositoryImpl.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitService.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitServiceImpl.java
  src/main/java/com/souf/soufwebsite/global/common/category/service/CategoryService.java
  src/main/java/com/souf/soufwebsite/global/config/SecurityConfig.java
Labels: fix, feat, refactor

#228 [FEAT] 견적받기 분기 분리
  src/main/java/com/souf/soufwebsite/domain/application/controller/RecruitApplicationApiSpecification.java
  src/main/java/com/souf/soufwebsite/domain/application/controller/RecruitApplicationController.java
  src/main/java/com/souf/soufwebsite/domain/application/controller/StudentApplicationApiSpecification.java
  src/main/java/com/souf/soufwebsite/domain/application/controller/StudentApplicationController.java
  src/main/java/com/souf/soufwebsite/domain/application/dto/req/ApplicationOfferReqDto.java
  src/main/java/com/souf/soufwebsite/domain/application/dto/res/ApplicantResDto.java
  src/main/java/com/souf/soufwebsite/domain/application/dto/res/MyApplicationResDto.java
  src/main/java/com/souf/soufwebsite/domain/application/entity/Application.java
  src/main/java/com/souf/soufwebsite/domain/application/exception/ErrorType.java
  src/main/java/com/souf/soufwebsite/domain/application/exception/OfferRequiredException.java
  src/main/java/com/souf/soufwebsite/domain/application/service/ApplicationService.java
  src/main/java/com/souf/soufwebsite/domain/application/service/ApplicationServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/req/RecruitReqDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/res/MyRecruitResDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/res/RecruitPopularityResDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/res/RecruitResDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/res/RecruitSimpleResDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/entity/PricePolicy.java
  src/main/java/com/souf/soufwebsite/domain/recruit/entity/Recruit.java
  src/main/java/com/souf/soufwebsite/domain/recruit/exception/ErrorType.java
  src/main/java/com/souf/soufwebsite/domain/recruit/exception/NotBlankPriceException.java
  src/main/java/com/souf/soufwebsite/domain/recruit/exception/NotValidPricePolicyException.java
  src/main/java/com/souf/soufwebsite/global/config/SecurityConfig.java
Labels: feat

#227 Feat: 후기 crud 기능 구현
  src/main/java/com/souf/soufwebsite/domain/application/service/ApplicationServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/chat/controller/ChatFileController.java
  src/main/java/com/souf/soufwebsite/domain/chat/service/ChatMessageService.java
  src/main/java/com/souf/soufwebsite/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/feed/repository/FeedCustomRepositoryImpl.java
  src/main/java/com/souf/soufwebsite/domain/feed/service/FeedConverter.java
  src/main/java/com/souf/soufwebsite/domain/feed/service/FeedServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/file/entity/Media.java
  src/main/java/com/souf/soufwebsite/domain/file/entity/PostType.java
  src/main/java/com/souf/soufwebsite/domain/file/repository/MediaRepository.java
  src/main/java/com/souf/soufwebsite/domain/file/service/FileService.java
  src/main/java/com/souf/soufwebsite/domain/member/controller/admin/AdminApiSpecification.java
  src/main/java/com/souf/soufwebsite/domain/member/controller/admin/AdminController.java
  src/main/java/com/souf/soufwebsite/domain/member/dto/ResDto/AdminPostResDto.java
  src/main/java/com/souf/soufwebsite/domain/member/dto/ResDto/AdminReportResDto.java
  src/main/java/com/souf/soufwebsite/domain/member/repository/MemberCustomRepositoryImpl.java
  src/main/java/com/souf/soufwebsite/domain/member/service/admin/AdminService.java
  src/main/java/com/souf/soufwebsite/domain/member/service/admin/AdminServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/member/service/favorite/FavoriteServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/member/service/general/MemberServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/recruit/entity/Recruit.java
  src/main/java/com/souf/soufwebsite/domain/recruit/exception/ErrorType.java
  src/main/java/com/souf/soufwebsite/domain/recruit/exception/NotCompletedTaskException.java
  src/main/java/com/souf/soufwebsite/domain/recruit/repository/RecruitCustomRepositoryImpl.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitScheduledService.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/report/dto/ReportReqDto.java
  src/main/java/com/souf/soufwebsite/domain/report/entity/Report.java
  src/main/java/com/souf/soufwebsite/domain/report/repository/ReportCustomRepository.java
  src/main/java/com/souf/soufwebsite/domain/report/repository/ReportCustomRepositoryImpl.java
  src/main/java/com/souf/soufwebsite/domain/review/controller/ReviewApiSpecification.java
  src/main/java/com/souf/soufwebsite/domain/review/controller/ReviewController.java
  src/main/java/com/souf/soufwebsite/domain/review/controller/ReviewSuccessMessage.java
  src/main/java/com/souf/soufwebsite/domain/review/dto/ReviewCreatedResDto.java
  src/main/java/com/souf/soufwebsite/domain/review/dto/ReviewDetailedResDto.java
  src/main/java/com/souf/soufwebsite/domain/review/dto/ReviewReqDto.java
  src/main/java/com/souf/soufwebsite/domain/review/dto/ReviewSearchReqDto.java
  src/main/java/com/souf/soufwebsite/domain/review/dto/ReviewSimpleResDto.java
  src/main/java/com/souf/soufwebsite/domain/review/entity/Review.java
  src/main/java/com/souf/soufwebsite/domain/review/entity/ReviewSortKey.java
  src/main/java/com/souf/soufwebsite/domain/review/exception/ErrorType.java
  src/main/java/com/souf/soufwebsite/domain/review/exception/NotFoundReviewException.java
  src/main/java/com/souf/soufwebsite/domain/review/exception/NotValidReviewAuthentication.java
  src/main/java/com/souf/soufwebsite/domain/review/repository/ReviewCustomRepository.java
  src/main/java/com/souf/soufwebsite/domain/review/repository/ReviewCustomRepositoryImpl.java
  src/main/java/com/souf/soufwebsite/domain/review/repository/ReviewRepository.java
  src/main/java/com/souf/soufwebsite/domain/review/service/ReviewScheduledService.java
  src/main/java/com/souf/soufwebsite/domain/review/service/ReviewService.java
  src/main/java/com/souf/soufwebsite/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/souf/soufwebsite/global/common/PostType.java
  src/main/java/com/souf/soufwebsite/global/common/viewCount/service/ViewCountService.java
  src/main/java/com/souf/soufwebsite/global/common/viewCount/service/ViewCountServiceImpl.java
  src/main/java/com/souf/soufwebsite/global/config/SecurityConfig.java
  src/main/java/com/souf/soufwebsite/global/redis/service/DistributedLockService.java
Labels: feat, refactor
