Repository Souf-Project/Souf-BE, pull requests merged in 2025-05, with the labels that each got.

#25 [Feat] Swagger API 구현
  build.gradle
  src/main/generated/com/souf/soufwebsite/domain/chat/entity/QChat.java
  src/main/generated/com/souf/soufwebsite/domain/feed/entity/QFeed.java
  src/main/generated/com/souf/soufwebsite/domain/recruit/entity/QRecruit.java
  src/main/generated/com/souf/soufwebsite/domain/user/entity/QUser.java
  src/main/java/com/souf/soufwebsite/domain/chat/entity/Chat.java
  src/main/java/com/souf/soufwebsite/domain/feed/entity/Feed.java
  src/main/java/com/souf/soufwebsite/domain/feed/service/FeedServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/member/controller/MemberController.java
  src/main/java/com/souf/soufwebsite/domain/member/dto/ReqDto/EditReqDto.java
  src/main/java/com/souf/soufwebsite/domain/member/dto/ReqDto/ResetReqDto.java
  src/main/java/com/souf/soufwebsite/domain/member/dto/ReqDto/SigninReqDto.java
  src/main/java/com/souf/soufwebsite/domain/member/dto/ReqDto/SignupReqDto.java
  src/main/java/com/souf/soufwebsite/domain/member/dto/ReqDto/UpdateReqDto.java
  src/main/java/com/souf/soufwebsite/domain/member/dto/ResDto/UserResDto.java
  src/main/java/com/souf/soufwebsite/domain/member/dto/TokenDto.java
  src/main/java/com/souf/soufwebsite/domain/member/entity/Member.java
  src/main/java/com/souf/soufwebsite/domain/member/entity/RoleType.java
  src/main/java/com/souf/soufwebsite/domain/member/reposiotry/MemberRepository.java
  src/main/java/com/souf/soufwebsite/domain/member/service/MemberService.java
  src/main/java/com/souf/soufwebsite/domain/member/service/MemberServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/recruit/entity/Recruit.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/user/dto/ReqDto/EditReqDto.java
  src/main/java/com/souf/soufwebsite/domain/user/dto/ResDto/UserResDto.java
  src/main/java/com/souf/soufwebsite/domain/user/reposiotry/UserRepository.java
  src/main/java/com/souf/soufwebsite/domain/user/service/UserService.java
  src/main/java/com/souf/soufwebsite/global/config/SecurityConfig.java
  src/main/java/com/souf/soufwebsite/global/config/SwaggerConfig.java
  src/main/java/com/souf/soufwebsite/global/email/EmailServiceImpl.java
  src/main/java/com/souf/soufwebsite/global/jwt/JwtAuthenticationProcessingFilter.java
  src/main/java/com/souf/soufwebsite/global/security/UserDetailsImpl.java
  src/main/java/com/souf/soufwebsite/global/util/SecurityUtils.java
  src/main/resources/application.yml
  src/test/java/com/souf/soufwebsite/domain/feed/service/FeedServiceImplTest.java
  src/test/java/com/souf/soufwebsite/domain/recruit/entity/RecruitTest.java
Labels: fix, feat, refactor

#28 [Fix] s3 업로드 방식 수정
  build.gradle
  src/main/java/com/souf/soufwebsite/domain/file/service/FileService.java
  src/main/java/com/souf/soufwebsite/domain/member/entity/Member.java
  src/main/java/com/souf/soufwebsite/domain/recruit/controller/RecruitController.java
  src/main/java/com/souf/soufwebsite/domain/recruit/controller/RecruitSuccessMessage.java
  src/main/java/com/souf/soufwebsite/domain/recruit/entity/Recruit.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitServiceImpl.java
  src/main/java/com/souf/soufwebsite/global/config/S3Config.java
  src/main/java/com/souf/soufwebsite/global/config/SecurityConfig.java
  src/main/java/com/souf/soufwebsite/global/jwt/JwtAuthenticationFilter.java
  src/main/resources/application.yml
  src/test/java/com/souf/soufwebsite/domain/file/service/FileServiceTest.java
  src/test/java/com/souf/soufwebsite/domain/recruit/entity/RecruitTest.java
  src/test/java/com/souf/soufwebsite/domain/recruit/service/RecruitServiceImplTest.java
Labels: fix, refactor

#31 [Feat] presigned url 반환 api 구현
  .gitignore
  src/main/generated/com/souf/soufwebsite/domain/chat/entity/QChat.java
  src/main/generated/com/souf/soufwebsite/domain/feed/entity/QFeed.java
  src/main/generated/com/souf/soufwebsite/domain/file/entity/QFile.java
  src/main/generated/com/souf/soufwebsite/domain/notification/entity/QNotification.java
  src/main/generated/com/souf/soufwebsite/domain/recruit/entity/QRecruit.java
  src/main/generated/com/souf/soufwebsite/global/common/QBaseEntity.java
  src/main/java/com/souf/soufwebsite/domain/feed/dto/FeedResDto.java
  src/main/java/com/souf/soufwebsite/domain/feed/service/FeedServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/file/controller/FileController.java
  src/main/java/com/souf/soufwebsite/domain/file/dto/FileDto.java
  src/main/java/com/souf/soufwebsite/domain/file/dto/FileReqDto.java
  src/main/java/com/souf/soufwebsite/domain/file/dto/PresignedUrlResDto.java
  src/main/java/com/souf/soufwebsite/domain/file/entity/File.java
  src/main/java/com/souf/soufwebsite/domain/file/service/FileService.java
  src/main/java/com/souf/soufwebsite/domain/file/service/S3UploaderService.java
  src/main/java/com/souf/soufwebsite/domain/recruit/controller/RecruitController.java
  src/main/java/com/souf/soufwebsite/domain/recruit/controller/RecruitSuccessMessage.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/RecruitCreateReqDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/RecruitReqDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/entity/Recruit.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitService.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitServiceImpl.java
  src/test/java/com/souf/soufwebsite/domain/file/service/FileServiceTest.java
  src/test/java/com/souf/soufwebsite/domain/file/service/S3UploaderServiceTest.java
Labels: fix, feat, refactor

#35 [Refactor] 공고문 api 기능 리팩터링
  src/main/java/com/souf/soufwebsite/domain/recruit/controller/RecruitController.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/RecruitReqDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/RecruitResDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/RecruitSimpleResDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/entity/Recruit.java
  src/main/java/com/souf/soufwebsite/domain/recruit/entity/RecruitCategoryMapping.java
  src/main/java/com/souf/soufwebsite/domain/recruit/repository/RecruitCategoryMappingRepository.java
  src/main/java/com/souf/soufwebsite/domain/recruit/repository/RecruitCustomRepository.java
  src/main/java/com/souf/soufwebsite/domain/recruit/repository/RecruitCustomRepositoryImpl.java
  src/main/java/com/souf/soufwebsite/domain/recruit/repository/RecruitRepository.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitService.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitServiceImpl.java
  src/main/java/com/souf/soufwebsite/global/common/BaseEntity.java
  src/main/java/com/souf/soufwebsite/global/common/FirstCategory.java
  src/main/java/com/souf/soufwebsite/global/common/category/CategoryService.java
  src/main/java/com/souf/soufwebsite/global/common/category/dto/CategoryDto.java
  src/main/java/com/souf/soufwebsite/global/common/category/entity/FirstCategory.java
  src/main/java/com/souf/soufwebsite/global/common/category/entity/SecondCategory.java
  src/main/java/com/souf/soufwebsite/global/common/category/entity/ThirdCategory.java
  src/main/java/com/souf/soufwebsite/global/common/category/exception/ErrorType.java
  src/main/java/com/souf/soufwebsite/global/common/category/exception/NotFoundFirstCategoryException.java
  src/main/java/com/souf/soufwebsite/global/common/category/exception/NotFoundSecondCategoryException.java
  src/main/java/com/souf/soufwebsite/global/common/category/exception/NotFoundThirdCategoryException.java
  src/main/java/com/souf/soufwebsite/global/common/category/repository/FirstCategoryRepository.java
  src/main/java/com/souf/soufwebsite/global/common/category/repository/SecondCategoryRepository.java
  src/main/java/com/souf/soufwebsite/global/common/category/repository/ThirdCategoryRepository.java
  src/main/java/com/souf/soufwebsite/global/config/JpaAuditingConfig.java
  src/main/java/com/souf/soufwebsite/global/config/QuerydslConfig.java
  src/main/java/com/souf/soufwebsite/global/config/RedisConfig.java
  src/main/java/com/souf/soufwebsite/global/redis/RedisProperties.java
  src/main/resources/application.yml
  src/test/java/com/souf/soufwebsite/domain/recruit/entity/RecruitTest.java
  src/test/java/com/souf/soufwebsite/domain/recruit/service/RecruitServiceImplTest.java
Labels: fix, feat, refactor

#38 [Fix] 피드 crud 리팩터링 및 기능 수정
  build.gradle
  gradlew.bat
  src/main/java/com/souf/soufwebsite/domain/feed/controller/FeedController.java
  src/main/java/com/souf/soufwebsite/domain/feed/controller/FeedSuccessMessage.java
  src/main/java/com/souf/soufwebsite/domain/feed/dto/FeedCreateReqDto.java
  src/main/java/com/souf/soufwebsite/domain/feed/dto/FeedDetailResDto.java
  src/main/java/com/souf/soufwebsite/domain/feed/dto/FeedReqDto.java
  src/main/java/com/souf/soufwebsite/domain/feed/dto/FeedResDto.java
  src/main/java/com/souf/soufwebsite/domain/feed/dto/FeedSimpleResDto.java
  src/main/java/com/souf/soufwebsite/domain/feed/entity/Feed.java
  src/main/java/com/souf/soufwebsite/domain/feed/entity/FeedTag.java
  src/main/java/com/souf/soufwebsite/domain/feed/entity/Tag.java
  src/main/java/com/souf/soufwebsite/domain/feed/exception/ErrorType.java
  src/main/java/com/souf/soufwebsite/domain/feed/repository/FeedRepository.java
  src/main/java/com/souf/soufwebsite/domain/feed/repository/FeedTagRepository.java
  src/main/java/com/souf/soufwebsite/domain/feed/repository/TagRepository.java
  src/main/java/com/souf/soufwebsite/domain/feed/service/FeedService.java
  src/main/java/com/souf/soufwebsite/domain/feed/service/FeedServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/feed/service/TagService.java
  src/main/java/com/souf/soufwebsite/domain/file/controller/FileController.java
  src/main/java/com/souf/soufwebsite/domain/file/dto/MediaReqDto.java
  src/main/java/com/souf/soufwebsite/domain/file/dto/MediaResDto.java
  src/main/java/com/souf/soufwebsite/domain/file/entity/FileType.java
  src/main/java/com/souf/soufwebsite/domain/file/entity/Media.java
  src/main/java/com/souf/soufwebsite/domain/file/entity/MediaType.java
  src/main/java/com/souf/soufwebsite/domain/file/repository/MediaRepository.java
  src/main/java/com/souf/soufwebsite/domain/file/service/FileService.java
  src/main/java/com/souf/soufwebsite/domain/file/service/S3UploaderService.java
  src/main/java/com/souf/soufwebsite/domain/member/controller/MemberController.java
  src/main/java/com/souf/soufwebsite/domain/member/dto/ResDto/MemberResDto.java
  src/main/java/com/souf/soufwebsite/domain/member/entity/Member.java
  src/main/java/com/souf/soufwebsite/domain/member/exception/ErrorType.java
  src/main/java/com/souf/soufwebsite/domain/member/exception/NotFoundMemberException.java
  src/main/java/com/souf/soufwebsite/domain/member/service/MemberService.java
  src/main/java/com/souf/soufwebsite/domain/member/service/MemberServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/recruit/controller/RecruitController.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/RecruitCreateResDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/entity/Recruit.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitService.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitServiceImpl.java
  src/main/java/com/souf/soufwebsite/global/common/BaseEntity.java
  src/main/java/com/souf/soufwebsite/global/config/SpringDataWebSupportConfig.java
  src/test/java/com/souf/soufwebsite/domain/file/service/S3UploaderServiceTest.java
Labels: fix, feat, refactor

#42 [Feat] ci cd 파이프라인 구축
  .github/workflows/CI-CD.yml
  Dockerfile
  docker-compose.yml
  src/main/java/com/souf/soufwebsite/global/common/HealthCheckController.java
  src/main/java/com/souf/soufwebsite/global/config/SecurityConfig.java
Labels: feat, refactor

#46 [Fix] 피드공고문 api swagger 적용
  src/main/java/com/souf/soufwebsite/domain/feed/controller/FeedApiSpecification.java
  src/main/java/com/souf/soufwebsite/domain/feed/controller/FeedController.java
  src/main/java/com/souf/soufwebsite/domain/feed/dto/FeedReqDto.java
  src/main/java/com/souf/soufwebsite/domain/file/dto/MediaReqDto.java
  src/main/java/com/souf/soufwebsite/domain/recruit/controller/RecruitApiSpecification.java
  src/main/java/com/souf/soufwebsite/domain/recruit/controller/RecruitController.java
  src/main/java/com/souf/soufwebsite/domain/recruit/dto/RecruitReqDto.java
  src/main/java/com/souf/soufwebsite/global/common/category/dto/CategoryDto.java
Labels: fix, refactor

#47 [Feat] 멤버 서비스 기능 수정 및 고도화
  src/main/java/com/souf/soufwebsite/domain/member/controller/MemberCategoryController.java
  src/main/java/com/souf/soufwebsite/domain/member/controller/MemberCategorySuccessMessage.java
  src/main/java/com/souf/soufwebsite/domain/member/controller/MemberController.java
  src/main/java/com/souf/soufwebsite/domain/member/dto/ReqDto/SignupReqDto.java
  src/main/java/com/souf/soufwebsite/domain/member/dto/ReqDto/UpdateReqDto.java
  src/main/java/com/souf/soufwebsite/domain/member/dto/ResDto/MemberResDto.java
  src/main/java/com/souf/soufwebsite/domain/member/entity/Member.java
  src/main/java/com/souf/soufwebsite/domain/member/entity/MemberCategoryMapping.java
  src/main/java/com/souf/soufwebsite/domain/member/exception/ErrorType.java
  src/main/java/com/souf/soufwebsite/domain/member/exception/NotAvailableEmailException.java
  src/main/java/com/souf/soufwebsite/domain/member/exception/NotMatchPasswordException.java
  src/main/java/com/souf/soufwebsite/domain/member/reposiotry/MemberCategoryMappingRepository.java
  src/main/java/com/souf/soufwebsite/domain/member/reposiotry/MemberCustomRepository.java
  src/main/java/com/souf/soufwebsite/domain/member/reposiotry/MemberCustomRepositoryImpl.java
  src/main/java/com/souf/soufwebsite/domain/member/reposiotry/MemberRepository.java
  src/main/java/com/souf/soufwebsite/domain/member/service/MemberCategoryService.java
  src/main/java/com/souf/soufwebsite/domain/member/service/MemberCategoryServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/member/service/MemberService.java
  src/main/java/com/souf/soufwebsite/domain/member/service/MemberServiceImpl.java
  src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitServiceImpl.java
  src/main/java/com/souf/soufwebsite/global/common/category/dto/CategoryDto.java
  src/main/java/com/souf/soufwebsite/global/common/category/dto/UpdateReqDto.java
  src/main/java/com/souf/soufwebsite/global/common/category/entity/FirstCategory.java
  src/main/java/com/souf/soufwebsite/global/common/category/entity/SecondCategory.java
  src/main/java/com/souf/soufwebsite/global/common/category/entity/ThirdCategory.java
  src/main/java/com/souf/soufwebsite/global/common/category/exception/ErrorType.java
  src/main/java/com/souf/soufwebsite/global/common/category/exception/NotFoundFirstCategoryException.java
  src/main/java/com/souf/soufwebsite/global/common/category/exception/NotFoundSecondCategoryException.java
  src/main/java/com/souf/soufwebsite/global/common/category/exception/NotFoundThirdCategoryException.java
  src/main/java/com/souf/soufwebsite/global/common/category/exception/NotIncludedFirstCategoryException.java
  src/main/java/com/souf/soufwebsite/global/common/category/exception/NotIncludedSecondCategoryException.java
  src/main/java/com/souf/soufwebsite/global/common/category/exception/NotMatchedCategoryException.java
  src/main/java/com/souf/soufwebsite/global/common/category/repository/FirstCategoryRepository.java
  src/main/java/com/souf/soufwebsite/global/common/category/repository/SecondCategoryRepository.java
  src/main/java/com/souf/soufwebsite/global/common/category/repository/ThirdCategoryRepository.java
  src/main/java/com/souf/soufwebsite/global/common/category/service/CategoryService.java
  src/test/java/com/souf/soufwebsite/domain/member/service/MemberCategoryServiceTest.java
Labels: fix, feat

#59 [FEAT] 이메일 인증 분리
  src/main/java/com/souf/soufwebsite/domain/member/controller/MemberApiSpecification.java
  src/main/java/com/souf/soufwebsite/domain/member/controller/MemberController.java
  src/main/java/com/souf/soufwebsite/domain/member/controller/auth/AuthApiSpecification.java
  src/main/java/com/souf/soufwebsite/domain/member/controller/auth/AuthController.java
  src/main/java/com/souf/soufwebsite/domain/member/reposiotry/MemberCustomRepository.java
  src/main/java/com/souf/soufwebsite/domain/member/reposiotry/MemberCustomRepositoryImpl.java
  src/main/java/com/souf/soufwebsite/domain/member/reposiotry/MemberRepository.java
  src/main/java/com/souf/soufwebsite/domain/member/service/MemberService.java
  src/main/java/com/souf/soufwebsite/domain/member/service/MemberServiceImpl.java
Labels: fix, refactor
